services:
  - type: web
    name: airlibrary-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT
        sync: false
      - key: WHATSAPP_BOT_NUMBER
        sync: false
      - key: MASTER_SHEET_ID
        sync: false
      - key: DRIVE_FOLDER_ID
        sync: false
      - key: WHATSAPP_AUTH_STATE
        sync: false 